### ISSUE TITLE
Luckysheet doesn't load due to "Circular dependency" ?

### ISSUE THREAD

**Issue by cl3f3** [YunoHost-Apps/luckysheet_ynh#5]
**Luckysheet doesn't load**
*At the first access to luckysheet, the browser stops at blue bar "loading"*

**Versions**
- Hardware: *Dedicated server - Debian 10*
- YunoHost version: 4.1.7.1 (stable)
- I have access to my server: *Through SSH&through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *no*

**To Reproduce**
*Steps to reproduce the behavior.*
   1. Install luckysheet
   2. Charge Luckysheet page

**Expected behavior**
*Site blocked at bluebar "charging".*

**Logs /var/www/luckysheet/.npm/_logs**
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/opt/node_n/n/versions/node/14.15.4/bin/node',
1 verbose cli   '/opt/node_n/n/versions/node/14/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v14.15.4
4 verbose config Skipping project config: /var/www/luckysheet/.npmrc. (matches userconfig)
5 verbose run-script [ 'predev', 'dev', 'postdev' ]
6 info lifecycle luckysheet@2.1.13~predev: luckysheet@2.1.13
7 info lifecycle luckysheet@2.1.13~dev: luckysheet@2.1.13
8 verbose lifecycle luckysheet@2.1.13~dev: unsafe-perm in lifecycle true
9 verbose lifecycle luckysheet@2.1.13~dev: PATH: /opt/node_n/n/versions/node/14.15.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/luckysheet/node_modules/.bin:/opt/node_n/n/versions/node/14/bin:/opt/nod$
10 verbose lifecycle luckysheet@2.1.13~dev: CWD: /var/www/luckysheet
11 silly lifecycle luckysheet@2.1.13~dev: Args: [ '-c', 'cross-env NODE_ENV=development gulp dev' ]
12 silly lifecycle luckysheet@2.1.13~dev: Returned: code: 1  signal: null
13 info lifecycle luckysheet@2.1.13~dev: Failed to exec dev script
14 verbose stack Error: luckysheet@2.1.13 dev: `cross-env NODE_ENV=development gulp dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/opt/node_n/n/versions/node/14.15.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:315:20)
14 verbose stack     at ChildProcess.<anonymous> (/opt/node_n/n/versions/node/14.15.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:315:20)
14 verbose stack     at maybeClose (internal/child_process.js:1048:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
15 verbose pkgid luckysheet@2.1.13
16 verbose cwd /var/www/luckysheet
17 verbose Linux 4.19.62-mod-std-ipv6-64-rescue
18 verbose argv "/opt/node_n/n/versions/node/14.15.4/bin/node" "/opt/node_n/n/versions/node/14/bin/npm" "run" "dev"
19 verbose node v14.15.4
20 verbose npm  v6.14.10
21 error code ELIFECYCLE
22 error errno 1
23 error luckysheet@2.1.13 dev: `cross-env NODE_ENV=development gulp dev`
23 error Exit status 1
24 error Failed at the luckysheet@2.1.13 dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

** Log 2 /yunohost/admin/#/services/luckysheet**
`-- Logs begin at Tue 2021-01-19 16:42:53 CET, end at Thu 2021-02-11 22:13:09 CET. --`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/select.js -> src/global/formula.js -> src/controllers/sheetmanage.js -> src/global/cleargridelement.js -> src/controllers/selection.js -> src/controllers/conditionformat.js -> src/controllers/select.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/sheetmanage.js -> src/global/cleargridelement.js -> src/controllers/selection.js -> src/controllers/conditionformat.js -> src/controllers/sheetmanage.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/global/formula.js -> src/controllers/sheetmanage.js -> src/global/cleargridelement.js -> src/controllers/selection.js -> src/global/formula.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/select.js -> src/global/formula.js -> src/controllers/sheetmanage.js -> src/global/cleargridelement.js -> src/controllers/selection.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/menuButton.js -> src/controllers/select.js -> src/global/formula.js -> src/controllers/sheetmanage.js -> src/global/cleargridelement.js -> src/controllers/menuButton.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/select.js -> src/global/formula.js -> src/controllers/sheetmanage.js -> src/global/createdom.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/global/formula.js -> src/controllers/sheetmanage.js -> src/global/formula.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/select.js -> src/global/formula.js -> src/controllers/sheetmanage.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/select.js -> src/global/formula.js -> src/controllers/sheetmanage.js -> src/controllers/select.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/select.js -> src/global/formula.js -> src/controllers/sheetmanage.js -> src/expendPlugins/chart/plugin.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/global/formula.js -> src/controllers/sheetmanage.js -> src/expendPlugins/chart/plugin.js -> src/global/formula.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/select.js -> src/global/formula.js -> src/controllers/sheetmanage.js -> src/expendPlugins/chart/plugin.js -> src/function/func.js -> src/global/func_methods.js -> src/utils/util.js`

`févr. 11 21:54:17 npm[22999]: Circular dependency: src/global/formula.js -> src/controllers/sheetmanage.js -> src/expendPlugins/chart/plugin.js -> src/function/func.js -> src/global/func_methods.js -> src/global/formula.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/global/formula.js -> src/controllers/sheetmanage.js -> src/expendPlugins/chart/plugin.js -> src/function/func.js -> src/global/formula.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/select.js -> src/global/formula.js -> src/controllers/sheetmanage.js -> src/expendPlugins/chart/plugin.js -> src/function/func.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/select.js -> src/global/formula.js -> src/controllers/sheetmanage.js -> src/controllers/zoom.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/sheetmanage.js -> src/controllers/zoom.js -> src/controllers/sheetmanage.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/menuButton.js -> src/controllers/select.js -> src/global/formula.js -> src/controllers/sheetmanage.js -> src/controllers/menuButton.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/menuButton.js -> src/controllers/select.js -> src/global/formula.js -> src/controllers/menuButton.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/select.js -> src/global/formula.js -> src/controllers/select.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/moreFormat.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/menuButton.js -> src/controllers/moreFormat.js -> src/controllers/menuButton.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/searchReplace.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/locationCell.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/menuButton.js -> src/controllers/ifFormulaGenerator.js -> src/controllers/updateCell.js -> src/controllers/menuButton.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/menuButton.js -> src/controllers/ifFormulaGenerator.js -> src/controllers/updateCell.js -> src/controllers/cellDatePickerCtrl.js -> src/controllers/menuButton.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/ifFormulaGenerator.js -> src/controllers/updateCell.js -> src/controllers/cellDatePickerCtrl.js -> src/global/api.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/menuButton.js -> src/controllers/ifFormulaGenerator.js ``-> src/controllers/updateCell.js -> src/controllers/cellDatePickerCtrl.js -> src/global/api.js -> src/controllers/menuButton.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/global/api.js -> src/controllers/controlHistory.js -> src/global/api.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/controllers/updateCell.js -> src/controllers/cellDatePickerCtrl.js -> src/global/api.js -> src/controllers/updateCell.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/ifFormulaGenerator.js -> src/controllers/updateCell.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/ifFormulaGenerator.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/controllers/insertFormula.js -> src/utils/util.js`
`févr. 11 21:54:17 npm[22999]: Circular dependency: src/utils/util.js -> src/controllers/menuButton.js -> src/utils/util.js`
`févr. 11 21:54:21 npm[22999]: [21:54:21] Finished 'core' after 35 s`
`févr. 11 21:54:21 npm[22999]: [21:54:21] Starting 'watcher'...`
`févr. 11 21:54:26 npm[22999]: [21:54:26] Finished 'watcher' after 5.72 s`
`févr. 11 21:54:26 npm[22999]: [21:54:26] Starting 'serve'...`
`févr. 11 21:54:27 npm[22999]: [Browsersync] Access URLs:`
`févr. 11 21:54:27 npm[22999]:  --------------------------------------`
`févr. 11 21:54:27 npm[22999]:        Local: http://localhost:3001`
`févr. 11 21:54:27 npm[22999]:     External: http://XX.XX.XX.XX:3001`
`févr. 11 21:54:27 npm[22999]:  --------------------------------------`
`févr. 11 21:54:27 npm[22999]:           UI: http://localhost:3002`
`févr. 11 21:54:27 npm[22999]:  UI External: http://localhost:3002`
`févr. 11 21:54:27 npm[22999]:  --------------------------------------`
`févr. 11 21:54:27 npm[22999]: [Browsersync] Serving files from: dist`
`févr. 11 21:54:27 npm[22999]: [21:54:27] Finished 'serve' after 516 ms`
`févr. 11 21:54:27 npm[22999]: [21:54:27] Finished 'dev' after 41 s`
'févr. 11 21:54:27 npm[22999]: [Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)`

**Comment by jcn50** [comment]
Almost a year and still no fixed~~
